//////////////////////to store the marks week wise, initial developement was  based kon this logioc biut now all the marks are 
    // stored in array so we dont need this]]]]]]]]]]]]]]
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bishal Shrestha
 */
public class form_WDF extends javax.swing.JFrame {
SemDFAssesment semdfassessment = new SemDFAssesment();
    /**
     * Creates new form form_WDF
     */
    public form_WDF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_week1 = new javax.swing.JButton();
        btn_week2 = new javax.swing.JButton();
        btn_week3 = new javax.swing.JButton();
        btn_week4 = new javax.swing.JButton();
        btn_week5 = new javax.swing.JButton();
        btn_week6 = new javax.swing.JButton();
        btn_week7 = new javax.swing.JButton();
        btn_week8 = new javax.swing.JButton();
        btn_week10 = new javax.swing.JButton();
        btn_week9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_week1.setText("Week 1");
        btn_week1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week1ActionPerformed(evt);
            }
        });

        btn_week2.setText("Week 2");
        btn_week2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week2ActionPerformed(evt);
            }
        });

        btn_week3.setText("Week 3");
        btn_week3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week3ActionPerformed(evt);
            }
        });

        btn_week4.setText("Week 4");
        btn_week4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week4ActionPerformed(evt);
            }
        });

        btn_week5.setText("Week 5");
        btn_week5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week5ActionPerformed(evt);
            }
        });

        btn_week6.setText("Week 4");
        btn_week6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week6ActionPerformed(evt);
            }
        });

        btn_week7.setText("Week 7");
        btn_week7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week7ActionPerformed(evt);
            }
        });

        btn_week8.setText("Week 8");
        btn_week8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week8ActionPerformed(evt);
            }
        });

        btn_week10.setText("Week 10");
        btn_week10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week10ActionPerformed(evt);
            }
        });

        btn_week9.setText("Week 9");
        btn_week9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_week9ActionPerformed(evt);
            }
        });

        jLabel1.setText("Weekly Discussion Forum Marks");

        jLabel2.setText("Weekly weighting over 10 weeks: 15%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_week9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_week10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_week7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_week8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_week5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_week3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_week4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addComponent(btn_week6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_week1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_week2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_week1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_week2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_week3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_week4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_week6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_week5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_week8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_week7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_week9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_week10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_week1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week1ActionPerformed
    // int week1 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 1")); 
    // semdfassessment.validateMarks("1", week1);
    }//GEN-LAST:event_btn_week1ActionPerformed

    private void btn_week2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week2ActionPerformed
    //  int week2 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 2")); 
     //  semdfassessment.validateMarks("2", week2);
    }//GEN-LAST:event_btn_week2ActionPerformed

    private void btn_week3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week3ActionPerformed
    //  int week3 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 3")); 
     //  semdfassessment.validateMarks("3", week3);
    }//GEN-LAST:event_btn_week3ActionPerformed

    private void btn_week4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week4ActionPerformed
      // int week4 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 4")); 
   //    semdfassessment.validateMarks("4", week4);
    }//GEN-LAST:event_btn_week4ActionPerformed

    private void btn_week5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week5ActionPerformed
     //  int week5 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 5")); 
     //  semdfassessment.validateMarks("5", week5);
    }//GEN-LAST:event_btn_week5ActionPerformed

    private void btn_week6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week6ActionPerformed
    //   int week6 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 6")); 
   //    semdfassessment.validateMarks("6", week6);
    }//GEN-LAST:event_btn_week6ActionPerformed

    private void btn_week7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week7ActionPerformed
     //   int week7 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 7")); 
     //  semdfassessment.validateMarks("7", week7);
    }//GEN-LAST:event_btn_week7ActionPerformed

    private void btn_week8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week8ActionPerformed
      //  int week8 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 8")); 
      //  semdfassessment.validateMarks("8", week8);
    }//GEN-LAST:event_btn_week8ActionPerformed

    private void btn_week10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week10ActionPerformed
    //  int week10 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 10")); 
    //   semdfassessment.validateMarks("10", week10);
    }//GEN-LAST:event_btn_week10ActionPerformed

    private void btn_week9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_week9ActionPerformed
     //  int week9 = Integer.parseInt(JOptionPane.showInputDialog("Enter Weekly Discussion Forum Marks for Week 9")); 
     //  semdfassessment.validateMarks("9", week9);
    }//GEN-LAST:event_btn_week9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_WDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_WDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_WDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_WDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_WDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_week1;
    private javax.swing.JButton btn_week10;
    private javax.swing.JButton btn_week2;
    private javax.swing.JButton btn_week3;
    private javax.swing.JButton btn_week4;
    private javax.swing.JButton btn_week5;
    private javax.swing.JButton btn_week6;
    private javax.swing.JButton btn_week7;
    private javax.swing.JButton btn_week8;
    private javax.swing.JButton btn_week9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
